# Generated by Django 3.2.9 on 2021-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('foto', models.ImageField(height_field=100, upload_to='', verbose_name='фото', width_field=100)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
